controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (randompick == 1) {
        info.changeScoreBy(1)
    }
    generate()
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (randompick == 0) {
        info.changeScoreBy(1)
    }
    generate()
})
function generate () {
    randompick = randint(0, 1)
    if (randompick == 0) {
        mySprite.sayText("\"push A\"")
    }
    if (randompick == 1) {
        mySprite.sayText("\"push B\"")
    }
}
let randompick = 0
let mySprite: Sprite = null
game.splash("\"Push A or B as Directed\" ")
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
info.startCountdown(20)
generate()
